// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations.AiMigrations
{
    [DbContext(typeof(AiDbContext))]
    [Migration("20251102002624_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AICallLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<int>("ConfigId")
                        .HasColumnType("int")
                        .HasColumnName("config_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("MatrixId")
                        .HasColumnType("int")
                        .HasColumnName("matrix_id");

                    b.Property<string>("RequestData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("request_data");

                    b.Property<string>("RequestText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("request_text");

                    b.Property<string>("ResponseData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_data");

                    b.Property<string>("ResponseText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_text");

                    b.Property<string>("ServiceName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("service_name");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("LogId");

                    b.HasIndex("ConfigId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("MatrixId");

                    b.HasIndex("StudentId");

                    b.ToTable("ai_call_logs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AIConfig", b =>
                {
                    b.Property<int>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("config_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfigId"));

                    b.Property<string>("ConfigDetails")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("config_details");

                    b.Property<string>("ConfigName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("config_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int?>("MaxTokens")
                        .HasColumnType("int")
                        .HasColumnName("max_tokens");

                    b.Property<string>("ModelName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("model_name");

                    b.Property<string>("SettingsJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("settings_json");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("temperature");

                    b.HasKey("ConfigId");

                    b.HasIndex("IsActive");

                    b.HasIndex("TeacherId");

                    b.HasIndex("TeacherId", "IsActive");

                    b.ToTable("ai_configs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AIHistoryChat", b =>
                {
                    b.Property<int>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("chat_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatId"));

                    b.Property<string>("ChatSummary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("chat_summary");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.HasKey("ChatId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TeacherId");

                    b.ToTable("ai_history_chats", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AICallLog", b =>
                {
                    b.HasOne("Domain.Entities.AIConfig", "AIConfig")
                        .WithMany("AICallLogs")
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AIConfig");
                });

            modelBuilder.Entity("Domain.Entities.AIConfig", b =>
                {
                    b.Navigation("AICallLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
